// <auto-generated />
namespace Digital_Planner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixSecurityStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixSecurityStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201711290205506_Fix-Security-Stamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
